### ISSUE TITLE
Create readme for the application

### ISSUE THREAD

**Issue by ChinmayMhatre** [ChinmayMhatre/NodePass#1]
- Create a readme.md file.

- Here are the contents to be added
   -  Heading : NodePass
   -  Description : A simple password generator created using nodeJS
   -  Packages used : **commander** - For creating options , **chalk** - styling console output ,  **clipboardy** - copying generated password in the clipboard
   - Usage :  
         -  Clone this repository to your system using ` git clone https://github.com/ChinmayMhatre/NodePass.git `
         - run `npm install` to install all the dependancies
         - run `npm link` to use the package globally on your system
         
   - syntax : 
     Run this command in the command line or terminal anywhere in your file structure
         ```
         nodepass [options]
         ```
   - List of commands
      - Use this screenshot to add each command as a code block like this `code block`
      -  ![image](https://user-images.githubusercontent.com/51131670/127963755-fc125c76-96c4-4350-81b1-39569e03d1fc.png)
    
   - Note : The password.txt file will be generated in the project folder

**Comment by sahithyandev** [comment]
I made a PR for this #6
